plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRailsVersion: 8.1
  Exclude:
    - 'bin/**/*'
    - '**/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/MissingSuper:
  AllowedParentClasses:
    - BaseService
    - Postnhost::BaseService

Style/Documentation:
  Enabled: false

Style/EmptyLiteral:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/StrongParametersExpect:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

FactoryBot/ExcessiveCreateList:
  Enabled: false
