# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=4.0.6
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

ARG BUNDLER_VERSION=4.0.19
RUN gem update --system --no-document && \
    gem install -N bundler -v $BUNDLER_VERSION

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      chromium \
      chromium-driver \
      curl \
      fonts-liberation \
      libffi-dev \
      libjemalloc2 \
      libvips \
      libyaml-dev \
      node-gyp \
      pkg-config \
      python-is-python3 \
      sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ARG NODE_VERSION=24.19.0
ARG YARN_VERSION=1.22.22
ENV PATH=/usr/local/node/bin:$PATH \
    RAILS_ENV=development
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    gem install foreman --no-document

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 3000
CMD ["bin/dev"]
